kind = "web"
previewPath = "/"
title = "Sentinel-AI"
version = "1.0.0"
id = "artifacts/sentinel-ai"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23148

[services.development]
run = "pnpm --filter @workspace/sentinel-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sentinel-ai", "run", "build" ]
publicDir = "artifacts/sentinel-ai/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23148"
BASE_PATH = "/"
